on:
  push:
    branches:
      - main
      - "release/**"
    paths:
      - "src/**"
      - "test/**"
      - "package.json"

  pull_request:
    branches:
      - main
      - "release/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.8.0

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test